import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Orbitron } from "next/font/google"; // gecici

import { cn } from "@/lib/utils";


const impact = localFont({
  src: "./fonts/impact.woff",
});

const inter = impact; // gecici

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn(`font-impact bg-default-black text-default-white `)}>{children}</body>
    </html>
  );
}
